# Generated by Django 2.1.5 on 2019-07-26 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0006_remove_fs_match_opp_gbc4'),
        ('users', '0002_auto_20190725_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roster125',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r125', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster61',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r61', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster65',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r65', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster70',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r70', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster74',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r74', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster79',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r79', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster86',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r86', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster92',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r92', to='vws_main.FS_Wrestler'),
        ),
        migrations.AddField(
            model_name='profile',
            name='roster97',
            field=models.ForeignKey(default='Yianni Diakomihalis', on_delete=django.db.models.deletion.CASCADE, related_name='r97', to='vws_main.FS_Wrestler'),
        ),
    ]
