# Generated by Django 2.1.7 on 2019-10-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0006_remove_fs_match_opp_gbc4'),
        ('users', '0005_auto_20190725_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='roster125',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster57',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster61',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster65',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster70',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster74',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster79',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster86',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster92',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='roster97',
        ),
        migrations.AddField(
            model_name='profile',
            name='roster',
            field=models.ManyToManyField(related_name='roster', to='vws_main.FS_Wrestler'),
        ),
    ]
