# Generated by Django 2.1.7 on 2019-10-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191002_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='mini.png', upload_to='profile_pics'),
        ),
    ]
