# Generated by Django 2.1.5 on 2019-01-14 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchdata',
            fields=[
                ('matchID', models.CharField(max_length=140, primary_key=True, serialize=False, unique=True)),
                ('date', models.CharField(max_length=140)),
                ('blue', models.CharField(max_length=140)),
                ('red', models.CharField(max_length=140)),
                ('blue_score', models.IntegerField()),
                ('red_score', models.IntegerField()),
                ('result', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_num', models.IntegerField()),
                ('event_lab', models.CharField(max_length=140)),
                ('event_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blue', models.CharField(max_length=140)),
                ('red', models.CharField(max_length=140)),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vws_main.Matchdata')),
            ],
        ),
        migrations.CreateModel(
            name='Wrestler',
            fields=[
                ('name', models.CharField(max_length=140, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=140)),
                ('eligibility', models.CharField(max_length=140)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
