# Generated by Django 2.1.5 on 2019-01-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
        ),
    ]
