# Generated by Django 2.1.5 on 2019-01-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='competitions',
            field=models.CharField(default='o', max_length=140),
        ),
    ]
