# Generated by Django 2.1.5 on 2019-01-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSeries',
        ),
    ]
