# Generated by Django 2.1.5 on 2019-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0002_remove_fs_wrestler_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fs_wrestler',
            name='team',
            field=models.ManyToManyField(related_name='team_name2', to='vws_main.FS_Team'),
        ),
    ]
