# Generated by Django 2.1.5 on 2019-01-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0002_delete_timeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(max_length=140)),
                ('event_num', models.IntegerField()),
                ('event_lab', models.CharField(max_length=140)),
                ('event_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blue', models.CharField(max_length=140)),
                ('red', models.CharField(max_length=140)),
            ],
        ),
    ]
