# Generated by Django 2.1.5 on 2019-01-16 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0002_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=140, primary_key=True, serialize=False, unique=True)),
        ),
        migrations.AddField(
            model_name='wrestler',
            name='team',
            field=models.ForeignKey(default='no team', on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='vws_main.Team'),
            preserve_default=False,
        ),
    ]
