# Generated by Django 2.1.5 on 2019-05-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0002_auto_20190512_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'FolkStyle Team', 'verbose_name_plural': 'FolkStyle Teams'},
        ),
        migrations.AlterModelOptions(
            name='wrestler',
            options={'verbose_name': 'FolkStyle Wrestler', 'verbose_name_plural': 'FolkStyle Wrestlers'},
        ),
    ]
