# Generated by Django 2.1.5 on 2019-05-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0003_fs_wrestler_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fs_wrestler',
            name='team',
        ),
        migrations.AddField(
            model_name='fs_wrestler',
            name='team',
            field=models.ForeignKey(default='Finger Lakes Wrestling Club/Titan Mercury Wrestling Club', on_delete=django.db.models.deletion.CASCADE, related_name='team_name2', to='vws_main.FS_Team'),
        ),
    ]
