# Generated by Django 2.1.5 on 2019-01-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0003_auto_20190115_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='blue_team',
            field=models.ForeignKey(default='no team', on_delete=django.db.models.deletion.CASCADE, related_name='blue_team_name', to='vws_main.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchdata',
            name='red_team',
            field=models.ForeignKey(default='no team', on_delete=django.db.models.deletion.CASCADE, related_name='red_team_name', to='vws_main.Team'),
            preserve_default=False,
        ),
    ]
