# Generated by Django 2.1.5 on 2019-07-15 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0004_auto_20190529_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='focus',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='focus_team',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='opp_team',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='timeseries',
            name='matchID',
        ),
        migrations.RemoveField(
            model_name='wrestler',
            name='team',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Matchdata',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Timeseries',
        ),
        migrations.DeleteModel(
            name='Wrestler',
        ),
    ]
