# Generated by Django 2.1.5 on 2019-05-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0004_auto_20190512_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='FS_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('date', models.DateField(null=True)),
                ('result', models.CharField(max_length=140, null=True)),
                ('slug', models.SlugField(default=models.CharField(max_length=140))),
                ('matches', models.ManyToManyField(related_name='events', to='vws_main.FS_Match')),
            ],
            options={
                'verbose_name': 'FreeStyle Event',
                'verbose_name_plural': 'FreeStyle Events',
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'FolStyle Event', 'verbose_name_plural': 'FolkStyle Events'},
        ),
    ]
