# Generated by Django 2.1.5 on 2019-01-17 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0004_auto_20190116_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('matches', models.ManyToManyField(related_name='events', to='vws_main.Matchdata')),
            ],
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='vws_main.Matchdata'),
        ),
    ]
