# Generated by Django 2.1.5 on 2019-05-12 18:53

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0005_auto_20190512_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_event',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name',), unique=True, verbose_name='slug'),
        ),
    ]
