# Generated by Django 2.1.5 on 2019-07-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0005_auto_20190715_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fs_match',
            name='opp_gbc4',
        ),
    ]
