# Generated by Django 2.1.7 on 2019-10-10 03:31

import django.core.files.storage
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0006_remove_fs_match_opp_gbc4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/reports'), upload_to='')),
                ('name', models.CharField(max_length=140)),
                ('date', models.DateField(null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name',), unique=True, verbose_name='slug')),
            ],
        ),
    ]
