# Generated by Django 2.1.5 on 2019-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0007_remove_fs_event_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrestler',
            name='eligibility',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=5),
        ),
    ]
