# Generated by Django 2.1.7 on 2019-10-13 14:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0008_auto_20191009_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/reports/'), upload_to='reports'),
        ),
    ]
