# Generated by Django 2.1.5 on 2019-05-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0009_remove_fs_match_gbc4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_ts',
            name='matchID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions2', to='vws_main.FS_Match'),
        ),
    ]
