# Generated by Django 2.1.5 on 2019-02-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0009_auto_20190201_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='focus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_wrestler', to='vws_main.Wrestler'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='focus_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='focus_team_name', to='vws_main.Team'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='opp_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_team_name', to='vws_main.Team'),
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opp_wrestler', to='vws_main.Wrestler'),
        ),
    ]
