# Generated by Django 2.1.7 on 2019-10-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0009_auto_20191013_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
