# Generated by Django 2.1.5 on 2019-05-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0010_auto_20190512_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_ts',
            name='event_time',
            field=models.CharField(max_length=140),
        ),
    ]
