# Generated by Django 2.1.5 on 2019-05-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0011_auto_20190512_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fs_event',
            name='matches',
            field=models.ManyToManyField(related_name='events2', to='vws_main.FS_Match'),
        ),
        migrations.AlterField(
            model_name='fs_match',
            name='duration',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
