# Generated by Django 2.1.5 on 2019-02-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0011_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrestler',
            name='competitions',
        ),
    ]
