# Generated by Django 2.1.5 on 2019-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0012_remove_wrestler_competitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='opp_stalling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='stalling',
            field=models.IntegerField(null=True),
        ),
    ]
