# Generated by Django 2.1.7 on 2019-03-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0013_auto_20190226_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='e_rate',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='opp_e_rate',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='opp_ride_rate',
        ),
        migrations.RemoveField(
            model_name='matchdata',
            name='ride_rate',
        ),
        migrations.AddField(
            model_name='matchdata',
            name='npf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='opp_npf',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
