# Generated by Django 2.1.5 on 2019-04-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vws_main', '0015_event_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrestler',
            name='eligibility',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
